import { Inter } from "next/font/google";
import { ChakraProvider, chakra } from "@chakra-ui/react";
import "./globals.css";
// import { Layout } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          {/* <Layout>{children}</Layout> */}
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
