export { default as Navbar } from "./Navbar";
export { default as Profile } from "./Profile";
export { default as About } from "./About";
export { default as Skills } from "./Skills";
export { default as SoftSkills } from "./SoftSkills";
export { default as GitHubActivity } from "./GitHubActivity";
export { default as Projects } from "./Projects";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
